# project language:
language: node_js

# node version:
node_js:
  - "8"

# virtual machine os (trusty - linux distributive)
dist: trusty

# additional services
services:
  - mongodb

# setup environment variables
env:
  - NODE_ENV=ci
  - PORT=3000

# speed up build process by caching node_modules directories
cache:
  directories:
    - node_modules
    - client/node_modules

# setup application
install:
  - npm install
  - npm run build

# command line operations
#
# nohup - if the shell is closed, dont kill processes this command creates
# & - run this command in a subshell - in the background
# sleep 3 - await 3 seconds before starting next command
# (to make sure that server is runnging)
# 
script:
  - nohup npm run start &
  - sleep 3
  - npm run test